config/routes.rb
Rails.application.routes.draw do
  resources :configuracoes
  resources :fidelidades
  resources :vendas
  resources :compras
  resources :estoques
  resources :promissorias
  resources :fornecedores
  resources :notafornecedores
  resources :promissoria
  resources :nota
  devise_for :usuarios
  resources :movimentos do
    get 'fluxo',            on: :collection
    get 'comprovante',      on: :collection
    get 'newdespesa',       on: :collection
    get 'despesapendente',  on: :collection
    get 'dre',              on: :collection
    get 'toogle_status',    on: :member
  end
  get   'clientes/busca'
  get   'clientes/fidelidade_busca'
  resources :clientes do
    get 'venda',              on: :member
    get 'ultimoagendamento',  on: :collection
    get 'agendamento',        on: :collection
  end
  resources :modopagamentos
  resources :categoriamovimentos
  get 'estatisticas' => 'estatisticas#index'
  root to: 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord

  validates :nome, :cidade, :uf, :telefone, :bairro, presence: true
  # validates :email, format: /[a-z|0-9]+@[a-z|0-9]+.[a-z]/

  has_many :movimento
  has_many :promissorias
  has_many :compras
  has_many :vendas
  has_many :fidelidade

  data = Date.today
  aniv = data.strftime('%d/%m')
  data_inicio = data.beginning_of_week
  data_fim = data.end_of_week

  scope :search_cliente, -> (nome) { where("unaccent(nome) ilike ?", "%#{nome}%") }

  semana = data_inicio.cweek

  scope :nomeduplicado, -> (nome) { where(nome: nome) }
  scope :aniversario_semana, -> { where(nascimento: semana) }

  scope :busca_cliente_fidelidade, -> (cliente) { joins(:fidelidade).where(nome: cliente) }


  self.per_page = 30
  #max_paginates_per 100
  def receitacliente
    @movimento = Movimento.find(cliente_id: @cliente)
  end

  def self.aniversariantes_do_dia(data_referencia = Date.today)
    where("to_char(data_nascimento, 'DD/MM') = ?", data_referencia.strftime('%d/%m')).
    sort_by { |a| a.data_nascimento.day }
  end

  def self.aniversariantes_da_semana(data_referencia = Date.today)
    inicio_semana = data_referencia.beginning_of_week.strftime('%m%d').to_i
    fim_semana = data_referencia.end_of_week.strftime('%m%d').to_i
    where("data_nascimento is not null and to_char(data_nascimento, 'MMDD')::int between ? and ?", inicio_semana, fim_semana ).
    sort_by { |a| a.data_nascimento.day }
  end

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :venda, :edit, :update, :destroy]

  respond_to :html

  # GET /clientes
  # GET /clientes.json
  def index
    #@clientes = Cliente.all
    @clientes = Cliente.order('nome').paginate(:page => params[:page], :per_page => 30)
    @clientes_total = Cliente.all.count
    # @clientes = Cliente.order(:nome).page params[:page]
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @pontual = Movimento.pontual(@cliente)
    @atrasada = Movimento.atrasada(@cliente)
    @fidelidade = Configuracao.first
  end

  def venda

  end

  def agendamento
    @clienteagenda = Cliente.where(cpf: params[:search])
    # if @clientes
    #   redirect_to new_cliente_path
    # else
    #   redirect_to @cliente.agendamento
    # end
  end

  def ultimoagendamento
    # @clientes = Cliente.all
  end

  def busca
    @busca_quem = params[:search]
    @clientebusca = Cliente.search_cliente(@busca_quem)
  end

  def fidelidade_busca
    @busca = params[:cliente]
    @clientebusca = Cliente.where(nome: @busca)
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit

  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)
    if !Cliente.nomeduplicado(@cliente.nome).present?
      @cliente.save
      respond_with(@cliente)
    else
      respond_to.html { redirect_to new_cliente_path, notice: 'Nome já cadastrado no sistema.' }
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    @cliente.update(cliente_params)
    respond_with(@cliente, location: cliente_path)
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cliente
    @cliente = Cliente.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cliente_params
    params.require(:cliente).permit(:nome, :email, :telefone, :cpf, :observacao, :cidade, :profissao, :uf, :data_nascimento, :endereco, :bairro, :estoque_ids,
    vendas_attributes: [:id, :cliente_id, :estoque_id, :quantidade, :_destroy])
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper

  def fidelidade_cont(ponto, fidelidade)
    if ponto == 4
      "warning"
    elsif ponto == fidelidade
      "c-white success"
    else
      ""
    end
  end

end

app/views/clientes/_form.html.erb
<%= simple_form_for(cliente, :html => {:multipart => true}) do |f| %>

<div class="row">
  <%= f.input :nome, wrapper: :material, wrapper_html: {class: 'col-md-8'} %>
  <%= f.input :data_nascimento, wrapper: :material, as: :localized, label: 'Data nascimento', placeholder: 'Data Prevista', wrapper_html: {class: 'col-md-2'}, input_html: {class: "date_field date-picker"} %>
  <%#= f.input :data_nascimento, wrapper: :material, wrapper_html: {class: 'col-md-2'}, input_html: {:maxlength => 5, :"data-mask" => "00/00/0000"}  %>
  <%= f.input :cpf, wrapper: :material, wrapper_html: {class: 'col-md-2'}, input_html: { :maxlength => 15, :"data-mask" => "000.000.000-00" } %>
</div>

<div class="row">
  <%= f.input :email, wrapper: :material, as: :email, wrapper_html: {class: 'col-md-4'} %>
  <%= f.input :telefone, wrapper: :material, wrapper_html: {class: 'col-md-2'}, input_html: { :maxlength => 15, :"data-mask" => "(00) 00000-0000" } %>
  <%= f.input :cidade, wrapper: :material, wrapper_html: {class: 'col-md-4'}, input_html: { :value => "Teresina"} %>
  <%= f.input :uf, wrapper: :material, wrapper_html: {class: 'col-md-2'}, input_html: { :value => "PI" } %>
</div>

<div class="row">
  <%= f.input :endereco, wrapper: :material, as: :text, label: 'Endereço',
  input_html: { cols: "40", rows: "2" },
  wrapper_html: {class: 'col-md-9'} %>
  <%= f.input :bairro, wrapper: :material, wrapper_html: {class: 'col-md-3'}%>
</div>

<div class="row">
  <%= f.input :observacao, wrapper: :material, as: :text, label: 'Observações',
  placeholder: 'Escreva aqui alguma informação adicional sobre esse lançamento',
  input_html: { cols: "50", rows: "3" },
  wrapper_html: {class: 'col-md-12'} %>
</div>

<div class="row">
  <button class="btn btn-primary" type="submit">Salvar</button>
  <%= link_to "Cancelar", :back, class: 'btn btn-default' %>
  <%= link_to "Apagar", @cliente,
  method: :delete,
  class: 'btn btn-danger pull-right',
    data: { confirm: 'Tem certeza que quer apagar?' } if @cliente.persisted? %>
  </div>

  <% end %>

app/views/clientes/_formvenda.html.erb
<%= simple_nested_form_for(cliente) do |f| %>

<div class="row">
  <div class="col-sm-8 m-b-25">
    <p><strong>Cliente:</strong> <%= @cliente.nome %></p>
    <p><strong>Endereço:</strong> <%= @cliente.endereco %></p>
    <p><strong>Bairro do Cliente:</strong> <%= @cliente.bairro %></p>

  </div>
</div>

<div class="row">
  <div class="col-sm-12 p-t-20">
    <button class="btn btn-primary" type="submit">Salvar</button>
    <%= link_to "Cancelar", :back, class: 'btn btn-default' %>
  </div>
</div>

<% end %>

app/views/clientes/agendamento.html.erb
<div class="c-header">
  <h2>Agendamento de cliente</h2>
</div>

<div class="card">

  <div class="card-header">
    <h2>Agendar cliente<small>Agendamento de procedimento de cliente</small></h2>
  </div>

  <div class="card-body table-responsive">

    <p id="notice" class="text-success"><%= notice %></p>

    <table class="table">
      <thead>
        <tr>
          <!-- <th>Img</th> -->
          <th>Nome</th>
          <th>Email</th>
          <th>Telefone</th>
          <th>Cpf</th>
          <th>Cidade-UF</th>
          <th colspan="3"><center>Ações</center></th>
        </tr>
      </thead>

      <tbody>

        <% @clienteagenda.each do |cliente| %>
        <tr>

          <td><%= cliente.nome %></td>
          <td><%= cliente.email %></td>
          <td><%= cliente.telefone %></td>
          <td><%= cliente.cpf %></td>
          <td><%= cliente.cidade %>-<%= cliente.uf %></td>
          <td><%= link_to 'Ver', cliente, class: "btn btn-info btn-xs" %></td>
          <td><%= link_to 'Editar', edit_cliente_path(cliente), class: "btn btn-warning btn-xs" %></td>
          <td><%= link_to 'Excluir', cliente, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger btn-xs" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <div class="form-group">
      <%#= link_to 'Novo cliente', new_cliente_path, class: "btn btn-primary" %>
    </div>

  </div>
</div>

app/views/clientes/busca.html.erb
<div class="card">

  <div class="card-header">
    <h2>Busca por: <u><%= @busca_quem  %></u></h2>
    <%= link_to  new_cliente_path, class: "btn btn-primary pull-right" do %>
    <i class="zmdi zmdi-plus-circle"></i> Cadastrar Novo
    <% end %>
  </div>

  <div class="card-body table-responsive">
    <p id="notice" class="text-success"><%= notice %></p>
    <% if @clientebusca.present? %>
    <table class="table">
      <thead>
        <tr>
          <!-- <th>Img</th> -->
          <th>Nome</th>
          <th>Telefone</th>
          <th>Cidade-UF</th>
          <th><center>Ações</center></th>
        </tr>
      </thead>

      <tbody>
        <% @clientebusca.each do |cliente| %>
        <tr>
          <td><%= link_to cliente.nome, cliente %></td>
          <td><%= cliente.telefone %></td>
          <td><%= cliente.cidade %>-<%= cliente.uf %></td>
          <td class="text-center" width="300">
            <%= link_to new_venda_path(cliente_id: cliente), class: "btn btn-primary btn-xs" do %>
  					<i class="zmdi zmdi-plus-circle"></i> Nova venda
  					<% end %>
            <%= link_to edit_cliente_path(cliente), class: "btn btn-default btn-xs" do %>
            <span class="zmdi zmdi-edit"></span> Editar
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <div class="card-body card-padding">
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        Ops, não existe nenhuma cliente com esse nome pesquisado.
      </div>
    </div>
    <% end %>
    <br>
    <div class="form-group">
      <%#= link_to 'Novo cliente', new_cliente_path, class: "btn btn-primary" %>
    </div>

  </div>
</div>

app/views/clientes/edit.html.erb
<div class="card">

  <div class="card-header">
    <h2>Editar cliente <small>Formulario para edição de clientes</small></h2>
  </div>

  <div class="card-body card-padding">
    <%= render 'form', cliente: @cliente %>
  </div>
</div>

app/views/clientes/fidelidade_busca.html.erb
<div class="card">

  <div class="card-header">
    <h2>Busca por: <u><%= @busca_quem  %></u></h2>
    <%= link_to  new_cliente_path, class: "btn btn-primary pull-right" do %>
    <i class="zmdi zmdi-plus-circle"></i> Cadastrar Novo
    <% end %>
  </div>

  <div class="card-body table-responsive">
    <p id="notice" class="text-success"><%= notice %></p>
    <% if @clientebusca.present? %>
    <table class="table">
      <thead>
        <tr>
          <!-- <th>Img</th> -->
          <th>Nome</th>
          <th>Telefone</th>
          <th>Cidade-UF</th>
          <th><center>Ações</center></th>
        </tr>
      </thead>

      <tbody>
        <% @clientebusca.each do |cliente| %>
        <tr>
          <td><%= link_to cliente.nome, cliente %></td>
          <td><%= cliente.telefone %></td>
          <td><%= cliente.cidade %>-<%= cliente.uf %></td>
          <td class="text-center" width="300">
            <%= link_to new_venda_path(cliente_id: cliente), class: "btn btn-primary btn-xs" do %>
  					<i class="zmdi zmdi-plus-circle"></i> Nova venda
  					<% end %>
            <%= link_to edit_cliente_path(cliente), class: "btn btn-default btn-xs" do %>
            <span class="zmdi zmdi-edit"></span> Editar
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <div class="card-body card-padding">
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        Ops, não existe nenhuma cliente com esse nome pesquisado.
      </div>
    </div>
    <% end %>
    <br>
    <div class="form-group">
      <%#= link_to 'Novo cliente', new_cliente_path, class: "btn btn-primary" %>
    </div>

  </div>
</div>

app/views/clientes/index.html.erb
<div class="c-header">
  <h2>Clientes</h2>
</div>

<div class="card">

  <div class="card-header">
    <h2>Clientes cadastrados <small>Total de clientes cadastrados: <strong><%= @clientes_total %></strong></small></h2>
  </div>

  <% if notice.present? %>
  <div class="card-body card-padding">
    <div class="alert <% if notice = 'Nome já cadastrado no sistema.' %> alert-danger <% else %> alert-success <% end %>alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <%= notice %>
    </div>
  </div>
  <% end %>

  <div class="card-body table-responsive">

    <table class="table">
      <thead>
        <tr>
          <!-- <th>Img</th> -->
          <th>Nome</th>
          <th>Telefone</th>
          <th>Cidade-UF</th>
          <th><center>Ações</center></th>
        </tr>
      </thead>

      <tbody>
        <% @clientes.each do |cliente| %>
        <tr>
          <td><%= link_to cliente.nome, cliente %></td>
          <td><%= cliente.telefone %></td>
          <td><%= cliente.cidade %>-<%= cliente.uf %></td>
          <td class="text-center" width="300">
            <%= link_to new_venda_path(cliente_id: cliente), class: "btn btn-primary btn-xs" do %>
  					<i class="zmdi zmdi-plus-circle"></i> Nova venda
  					<% end %>
            <%= link_to edit_cliente_path(cliente), class: "btn btn-default btn-xs" do %>
            <span class="zmdi zmdi-edit"></span> Editar
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <center><%= will_paginate @clientes %></center>
    <br>
    <div class="form-group">
      <%#= link_to 'Novo cliente', new_cliente_path, class: "btn btn-primary" %>
    </div>

  </div>
</div>

app/views/clientes/new.html.erb
<div class="card">
  <div class="card-header">
    <h2>Cadastrar novo cliente <small>formulário para cadastro de novo cliente</small></h2>
  </div>

  <div class="card-body card-padding">
    <% if notice.present? %>
    <div class="alert <% if notice = 'Nome já cadastrado no sistema.' %> alert-danger <% else %> alert-success <% end %>alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <%= notice %>
    </div>
    <% end %>

    <%= render 'form', cliente: @cliente %>
  </div>
</div>

app/views/clientes/show.html.erb
<div class="card">

	<div class="card-header">
		<h1>
			<i class="zmdi zmdi-pin-account zmdi-hc-fw"></i> <%= @cliente.nome %>
		</h1>

		<% if notice.present? %>
		<div class="card-body card-padding">
			<div class="alert <% if notice = 'Nome já cadastrado no sistema.' %> alert-danger <% else %> alert-success <% end %>alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
				<%= notice %>
			</div>
		</div>
		<% end %>
	</div>
	<div class="card-body card-padding">
		<div class="row">
			<div class="col-md-7 col-sm-6 p-5 m-t-5 m-b-15">
				<div class="table-responsive">
					<table class="table table-condensed">
						<thead>
							<tr>
								<th colspan=2 class="text-left cg-list cgl-main palette-Teal bg c-white">Dados </th>
							</tr>
						</thead>
						<tbody class="cg-list dark palette-Blue-Grey-50 bg">
							<tr>
								<td><i class="zmdi zmdi-flower"></i> Data Aniversário</td>
								<td><% if @cliente.data_nascimento.present? %> <%= @cliente.data_nascimento %><% else %><mark> <i> Não informado </i></mark> <% end %></td>
							</tr>
							<tr>
								<td><i class="zmdi zmdi-city"></i> Cidate-UF</td>
								<td><%= @cliente.cidade %>-<%= @cliente.uf %></td>
							</tr>
							<tr>
								<td><i class="zmdi zmdi-phone"></i> Telefone</td>
								<td><% if @cliente.telefone.present? %> <%= @cliente.telefone %> <% else %> <small><i>Não informado</i></small> <% end %></td>
							</tr>
							<tr>
								<td><i class="zmdi zmdi-account-box"></i> CPF</td>
								<td><% if @cliente.cpf.present? %> <%= @cliente.cpf %> <% else %> <small><i>Não informado</i></small><% end %></td>
							</tr>
							<tr>
								<td><i class="zmdi zmdi-account"></i> Email</td>
								<td> <% if @cliente.email.present? %> <%= @cliente.email %><% else %> <small><i>Não informado</i></small> <% end %></td>
							</tr>
							<tr>
								<td><i class="zmdi zmdi-local-offer"></i> Endereço</td>
								<td><% if @cliente.endereco.present? %> <%= @cliente.endereco %> <% else %> <small><i>Não informado</i></small><% end %></td>
							</tr>
							<tr>
								<td><i class="zmdi zmdi-local-offer"></i> Bairro</td>
								<td><% if @cliente.bairro.present? %> <%= @cliente.bairro %> <% else %> <small><i>Não informado</i></small><% end %></td>
							</tr>
							<tr>
								<td><i class="zmdi zmdi-comment-alt"></i> Descrição</td>
								<td><%= @cliente.observacao %></td>
							</tr>
						</table>
					</div>
					<br>
					<%= link_to new_venda_path(cliente_id: @cliente), class: "btn btn-primary" do %>
					<i class="zmdi zmdi-plus-circle"></i> Nova venda
					<% end %>
					<%= link_to edit_cliente_path(@cliente), class: "btn btn-warning" do %>
					<i class="zmdi zmdi-edit"></i> Editar
					<% end %>
					<%= link_to clientes_path, class: "btn btn-default" do %>
					<i class="zmdi zmdi-long-arrow-return"></i> Voltar
					<% end %>
					<%= link_to @cliente, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger pull-right" do %>
					<span class="zmdi zmdi-delete"></span> Excluir
					<% end %>
					<br>
				</div>
				<div class="col-md-5 col-sm-6 p-5 m-t-5 m-b-15">
					<div class="table-responsive">
						<table class="table table-condensed">
							<thead>
								<tr>
									<th colspan=2 class="text-left cg-list cgl-main palette-Teal bg c-white">Programa fidelidade</th>
								</tr>
							</thead>
							<tbody class="cg-list dark palette-Blue-Grey-50 bg">
								<tr>
									<td>Compras realizadas</td>
									<td><%= @cliente.vendas.count %></td>
								</tr>
								<% @total = Movimento.ver_pontuacao(@cliente) %>
								<tr class="<%= fidelidade_cont(@total, @fidelidade.fidelidade_valor) %>">
									<td>Pontos do cliente <small><i>(<%= @fidelidade.fidelidade_valor %> para desconto)</small></i></td>
									<td>
										<% if @total != @fidelidade.fidelidade_valor %>
										<%= @total %>
										<% elsif @total == @fidelidade.fidelidade_valor %>
										<strong>Pontuação alcançada! <%= @pontos_fidelidade %></strong>
										<%= link_to new_fidelidade_path(cliente_id: @cliente), class: "btn btn-primary btn-xs" do %>
										Validar desconto
										<% end %>
										<% end %>
									</td>
								</tr>
								<tr>
									<td>Fidelidade registradas</td>
									<td><%= @cliente.fidelidade.count %></td>

								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="card">
		<div class="action-header clearfix palette-Teal-400 bg">
			<div class="ah-label hidden-xs palette-White text">Últimas 20 compras</div>
			<div class="ah-search">
				<input type="text" placeholder="Start typing..." class="ahs-input">
				<i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
			</div>
			<ul class="ah-actions actions a-alt">
				<li>
					<a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
						<i class="zmdi zmdi-search"></i>
					</a>
				</li>
				<li class="dropdown">
					<a href="" data-toggle="dropdown" aria-expanded="true">
						<i class="zmdi zmdi-sort"></i>
					</a>
					<ul class="dropdown-menu dropdown-menu-right">
						<li>
							<%= link_to 'Data', cliente_path(order: "created_at") %>
						</li>
						<li>
							<%= link_to 'Descrição', cliente_path(order: "descricao") %>
						</li>

					</ul>
				</li>
				<li class="dropdown">
					<a href="" data-toggle="dropdown" aria-expanded="false">
						<i class="zmdi zmdi-more-vert"></i>
					</a>
					<ul class="dropdown-menu dropdown-menu-right">
						<li>
							<a href="">Refresh</a>
						</li>
						<li>
							<a href="">Listview Settings</a>
						</li>
					</ul>
				</li>
			</ul>
		</div>

		<div class="card-body card-padding">
			<% ver_promissorias.each do |cp| %>
			<div class="p-timeline">
				<div class="pt-line c-gray text-right">
					<span class="d-block"><strong><%= cp.created_at.year %></strong></span>
					<%= l cp.created_at, format: :resum %><br>
					<%= l cp.created_at, format: :hora %>
				</div>

				<div class="pt-body">
					<h2 class="ptb-title">
						<%= cp.descricao %>
					</h2>
					<div class="lightbox clearfix">
						<p class="">
							Valor total da compra: <strong><%= cp.valor_total %></strong><br>
						</p>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>

app/views/clientes/ultimoagendamento.html.erb
<div class="card">

  <div class="card-header">
    <h2>Clientes com mais de 30 dias <small>Lista de todas as clientes com mais de 30 dias sem agendar</small></h2>
  </div>

  <% if notice.present? %>
  <div class="card-body card-padding">
    <div class="alert <% if notice = 'Nome já cadastrado no sistema.' %> alert-danger <% else %> alert-success <% end %>alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <%= notice %>
    </div>
  </div>
  <% end %>

  <div class="card-body table-responsive">

    <table class="table">
      <thead>
        <tr>
          <!-- <th>Img</th> -->
          <th>Nome</th>
          <th>Telefone</th>
          <th class="text-right">Agendamento</th>
          <th>Cidade-UF</th>
          <th><center>Ações</center></th>
        </tr>
      </thead>
      <tbody>

        <%# @clientes.each do |client| %>
          <%# ultimo = client.agendamento.last %>


        <%# end %>
        <tr>
          <td> </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/clientes/venda.html.erb
<div class="card">
  <div class="card-header">
    <h2>Registrar venda para cliente </h2>
  </div>

  <div class="card-body card-padding">
    <% if notice.present? %>
    <div class="alert <% if notice = 'Nome já cadastrado no sistema.' %> alert-danger <% else %> alert-success <% end %>alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <%= notice %>
    </div>
    <% end %>

    <%= render 'formvenda', cliente: @cliente %>
  </div>
</div>