config/routes.rb
Rails.application.routes.draw do
  resources :configuracoes
  resources :fidelidades
  resources :vendas
  resources :compras
  resources :estoques
  resources :promissorias
  resources :fornecedores
  resources :notafornecedores
  resources :promissoria
  resources :nota
  devise_for :usuarios
  resources :movimentos do
    get 'fluxo',            on: :collection
    get 'comprovante',      on: :collection
    get 'newdespesa',       on: :collection
    get 'despesapendente',  on: :collection
    get 'dre',              on: :collection
    get 'toogle_status',    on: :member
  end
  get   'clientes/busca'
  get   'clientes/fidelidade_busca'
  resources :clientes do
    get 'venda',              on: :member
    get 'ultimoagendamento',  on: :collection
    get 'agendamento',        on: :collection
  end
  resources :modopagamentos
  resources :categoriamovimentos
  get 'estatisticas' => 'estatisticas#index'
  root to: 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fidelidade.rb
class Fidelidade < ApplicationRecord

  belongs_to :cliente

  scope :contafidelidade, -> (id) { where(cliente_id: id) }

end

app/controllers/fidelidades_controller.rb
class FidelidadesController < ApplicationController
  before_action :set_fidelidade, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @fidelidades = Fidelidade.all
    respond_with(@fidelidades)
  end

  def show
    respond_with(@fidelidade)
  end

  def new
    @fidelidade = Fidelidade.new
    @fidelidade.cliente_id = params[:cliente_id]
    respond_with(@fidelidade)
  end

  def edit
  end

  def create
    @fidelidade = Fidelidade.new(fidelidade_params)
    @fidelidade.save
    respond_with(@fidelidade, location: cliente_path(@fidelidade.cliente_id))
  end

  def update
    @fidelidade.update(fidelidade_params)
    respond_with(@fidelidade)
  end

  def destroy
    @fidelidade.destroy
    respond_with(@fidelidade)
  end

  private
  def set_fidelidade
    @fidelidade = Fidelidade.find(params[:id])
  end

  def fidelidade_params
    params.require(:fidelidade).permit(:quant_compra, :cliente_id)
  end
end

app/helpers/fidelidades_helper.rb
module FidelidadesHelper
end

app/views/fidelidades/_form.html.erb
<%= simple_form_for(fidelidade, multipart: true) do |f| %>

<% if fidelidade.errors.any? %>
<div id="error_explanation">
</div>
<% end %>

<div class="row">
  <%= f.hidden_field :cliente_id %>
  <%= f.hidden_field :quant_compra, value: "1" %>
  <strong>Cliente:</strong> <%= Cliente.find(@fidelidade.cliente_id).nome %>
</div>
<br><br>

<div class="row">
  <button class="btn btn-success" type="submit">Validar</button>
  <%= link_to "Cancelar", :back, class: 'btn btn-default' %>
  </div>

  <% end %>

app/views/fidelidades/edit.html.erb
<div class="card">

  <div class="card-header">
    <h2>Editar Fidelidade </h2>
  </div>

  <div class="card-body card-padding">
    <%= render 'form', fidelidade: @fidelidade %>
  </div>
</div>

app/views/fidelidades/index.html.erb
<div class="card">

  <div class="card-header">
    <h2>
      Fidelidades cadastrados
      <%= link_to new_fidelidade_path, class: 'btn btn-primary pull-right' do %>
      <span class='zmdi zmdi-plus-circle'></span> Nova Fidelidade
      <% end %>
    </h2>
  </div>

  <div class="card-body table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Descrição</th>
          <th>Data cadastro</th>
          <th>Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @fidelidades.each do |fidelidade| %>
        <tr>
          <td><%= link_to fidelidade.descricao, fidelidade %></td>
          <td><%= l fidelidade.created_at, format: :long %></td>
          <td>
            <%= link_to edit_fidelidade_path(fidelidade), class: 'btn btn-default btn-xs' do %>
              <span class="zmdi zmdi-edit"></span> Editar
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/fidelidades/new.html.erb
<div class="card">
  <div class="card-header">
    <h2>Validar fidelidade</h2>
  </div>

  <div class="card-body card-padding">
    <%= render 'form', fidelidade: @fidelidade %>
  </div>
</div>

app/views/fidelidades/show.html.erb
<div class="card">

  <div class="card-header">
    <h2><%= @fidelidade.descricao %> </h2>
  </div>

  <div class="card-body card-padding">
    <table class="table">
      <tr>
        <td class="col-md-2">Descrição</td> <td><%= @fidelidade.descricao %></td>
      </tr>
      <tr>
        <td>Data do cadastro</td> <td><%= l @fidelidade.created_at %></td>
      </tr>
    </table>

    <%= link_to "Editar", edit_fidelidade_path(@fidelidade), class: 'btn btn-warning' %>    
  </div>