config/routes.rb
Rails.application.routes.draw do
  resources :configuracoes
  resources :fidelidades
  resources :vendas
  resources :compras
  resources :estoques
  resources :promissorias
  resources :fornecedores
  resources :notafornecedores
  resources :promissoria
  resources :nota
  devise_for :usuarios
  resources :movimentos do
    get 'fluxo',            on: :collection
    get 'comprovante',      on: :collection
    get 'newdespesa',       on: :collection
    get 'despesapendente',  on: :collection
    get 'dre',              on: :collection
    get 'toogle_status',    on: :member
  end
  get   'clientes/busca'
  get   'clientes/fidelidade_busca'
  resources :clientes do
    get 'venda',              on: :member
    get 'ultimoagendamento',  on: :collection
    get 'agendamento',        on: :collection
  end
  resources :modopagamentos
  resources :categoriamovimentos
  get 'estatisticas' => 'estatisticas#index'
  root to: 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/categoriamovimento.rb
class Categoriamovimento < ApplicationRecord

  has_many :movimento

end

app/controllers/categoriamovimentos_controller.rb
class CategoriamovimentosController < ApplicationController
  before_action :set_categoriamovimento, only: [:show, :edit, :update, :destroy]

  # GET /categoriamovimentos
  # GET /categoriamovimentos.json
  def index
    @categoriamovimentos = Categoriamovimento.all
  end

  # GET /categoriamovimentos/1
  # GET /categoriamovimentos/1.json
  def show
  end

  # GET /categoriamovimentos/new
  def new
    @categoriamovimento = Categoriamovimento.new
  end

  # GET /categoriamovimentos/1/edit
  def edit
  end

  # POST /categoriamovimentos
  # POST /categoriamovimentos.json
  def create
    @categoriamovimento = Categoriamovimento.new(categoriamovimento_params)

    respond_to do |format|
      if @categoriamovimento.save
        format.html { redirect_to @categoriamovimento, notice: 'Categoriamovimento was successfully created.' }
        format.json { render :show, status: :created, location: @categoriamovimento }
      else
        format.html { render :new }
        format.json { render json: @categoriamovimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoriamovimentos/1
  # PATCH/PUT /categoriamovimentos/1.json
  def update
    respond_to do |format|
      if @categoriamovimento.update(categoriamovimento_params)
        format.html { redirect_to @categoriamovimento, notice: 'Categoriamovimento was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoriamovimento }
      else
        format.html { render :edit }
        format.json { render json: @categoriamovimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoriamovimentos/1
  # DELETE /categoriamovimentos/1.json
  def destroy
    @categoriamovimento.destroy
    respond_to do |format|
      format.html { redirect_to categoriamovimentos_url, notice: 'Categoriamovimento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoriamovimento
      @categoriamovimento = Categoriamovimento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoriamovimento_params
      params.require(:categoriamovimento).permit(:nome, :descricao, :movimento_id)
    end
end

app/views/categoriamovimentos/_form.html.erb
<%= form_for(categoriamovimento) do |f| %>
  <% if categoriamovimento.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(categoriamovimento.errors.count, "error") %> prohibited this categoriamovimento from being saved:</h2>

    <ul>
      <% categoriamovimento.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="form-group  col-sm-6 fg-float m-b-30">
      <div class="fg-line">
        <%= f.label :nome,"Nome*", class: "fg-label" %>
        <%= f.text_field :nome, class: "form-control" %>
      </div>
    </div>

    <div class="form-group  col-sm-9 fg-float m-b-30">
      <div class="fg-line">
        <%= f.text_area :descricao, class: "form-control" %>
        <%= f.label :descricao, "Descrição", class: "fg-label" %>
      </div>
    </div>
  </div>

  <div class="row">

    <div class="form-group  col-sm-9 fg-float m-b-30">
      <%= f.button 'Salvar', class: "btn btn-primary btn-lg" %>
      <%= link_to 'Voltar', categoriamovimentos_path, class: "btn btn-default" %>
    </div>
  </div>

  <% end %>

app/views/categoriamovimentos/edit.html.erb
<h1>Editing Categoriamovimento</h1>

<%= render 'form', categoriamovimento: @categoriamovimento %>

<%= link_to 'Show', @categoriamovimento %> |
<%= link_to 'Back', categoriamovimentos_path %>

app/views/categoriamovimentos/index.html.erb
<div class="card">

  <div class="card-header">
    <h2>Categoria de despesas
      <%= link_to new_categoriamovimento_path, class: 'btn btn-primary pull-right' do %>
      <span class="zmdi zmdi-plus-circle"></span> Nova categoria
      <% end %>
    </h2>
  </div>

  <div class="card-body table-responsive">

    <p id="notice" class="text-success"><%= notice %></p>

    <table class="table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Descricao</th>
          <th class="text-center">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @categoriamovimentos.each do |categoriamovimento| %>
        <tr>
          <td><%= categoriamovimento.nome %></td>
          <td><%= categoriamovimento.descricao %></td>
          <td class="text-center">
            <%= link_to 'Ver', categoriamovimento, class: "btn btn-info btn btn-xs" %>
            <%= link_to 'Editar', edit_categoriamovimento_path(categoriamovimento), class: "btn btn-warning btn-xs" %>
            <%= link_to 'Excluir', categoriamovimento, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: "btn btn-danger btn-xs" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>

  </div>
</div>

app/views/categoriamovimentos/new.html.erb
<div class="c-header">
  <h2>Categoria de despesas</h2>
</div>

<div class="card">

  <div class="card-header">
    <h2>Cadastrar nova categoria <small>Formulário para cadastro de nova categoria</small></h2>
  </div>

  <div class="card-body card-padding">
    <%= render 'form', categoriamovimento: @categoriamovimento %>
  </div>
</div>

app/views/categoriamovimentos/show.html.erb
<% if notice.present? %>
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
  <%= notice %>
</div>
<% end %>

<p>
  <strong>Nome:</strong>
  <%= @categoriamovimento.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @categoriamovimento.descricao %>
</p>

<p>
  <strong>Movimento:</strong>
  <%= @categoriamovimento.movimento_id %>
</p>

<%= link_to 'Edit', edit_categoriamovimento_path(@categoriamovimento) %> |
<%= link_to 'Back', categoriamovimentos_path %>