config/routes.rb
Rails.application.routes.draw do
  resources :configuracoes
  resources :fidelidades
  resources :vendas
  resources :compras
  resources :estoques
  resources :promissorias
  resources :fornecedores
  resources :notafornecedores
  resources :promissoria
  resources :nota
  devise_for :usuarios
  resources :movimentos do
    get 'fluxo',            on: :collection
    get 'comprovante',      on: :collection
    get 'newdespesa',       on: :collection
    get 'despesapendente',  on: :collection
    get 'dre',              on: :collection
    get 'toogle_status',    on: :member
  end
  get   'clientes/busca'
  get   'clientes/fidelidade_busca'
  resources :clientes do
    get 'venda',              on: :member
    get 'ultimoagendamento',  on: :collection
    get 'agendamento',        on: :collection
  end
  resources :modopagamentos
  resources :categoriamovimentos
  get 'estatisticas' => 'estatisticas#index'
  root to: 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord

  validates :nome, :cidade, :uf, :telefone, :bairro, presence: true
  # validates :email, format: /[a-z|0-9]+@[a-z|0-9]+.[a-z]/

  has_many :movimento
  has_many :promissorias
  has_many :compras
  has_many :vendas
  has_many :fidelidade

  data = Date.today
  aniv = data.strftime('%d/%m')
  data_inicio = data.beginning_of_week
  data_fim = data.end_of_week

  scope :search_cliente, -> (nome) { where("unaccent(nome) ilike ?", "%#{nome}%") }

  semana = data_inicio.cweek

  scope :nomeduplicado, -> (nome) { where(nome: nome) }
  scope :aniversario_semana, -> { where(nascimento: semana) }

  scope :busca_cliente_fidelidade, -> (cliente) { joins(:fidelidade).where(nome: cliente) }


  self.per_page = 30
  #max_paginates_per 100
  def receitacliente
    @movimento = Movimento.find(cliente_id: @cliente)
  end

  def self.aniversariantes_do_dia(data_referencia = Date.today)
    where("to_char(data_nascimento, 'DD/MM') = ?", data_referencia.strftime('%d/%m')).
    sort_by { |a| a.data_nascimento.day }
  end

  def self.aniversariantes_da_semana(data_referencia = Date.today)
    inicio_semana = data_referencia.beginning_of_week.strftime('%m%d').to_i
    fim_semana = data_referencia.end_of_week.strftime('%m%d').to_i
    where("data_nascimento is not null and to_char(data_nascimento, 'MMDD')::int between ? and ?", inicio_semana, fim_semana ).
    sort_by { |a| a.data_nascimento.day }
  end

end

app/models/movimento.rb
class Movimento < ApplicationRecord

  extend Enumerize

  validates :valor_previsto, :data_prevista, :tipo, presence: true

  usar_como_dinheiro :valor_previsto
  usar_como_dinheiro :valor_realizado
  usar_como_dinheiro :desconto
  usar_como_dinheiro :valor_cartao
  usar_como_dinheiro :valor_dinheiro

  has_many :pagamento
  has_many :promissorias, through: :pagamento
  belongs_to :cliente
  belongs_to :venda, optional: true
  belongs_to :categoriamovimento, optional: true
  belongs_to :agendamento, optional: true
  belongs_to :modopagamento, optional: true

  scope :conta_fidelidade, -> (id) { joins(:cliente).where(fidelidade: true, cliente_id: id) }

  before_save :altera_valor
  def altera_valor
    if self.desconto.present?
      desconto_passado = self.desconto
      self.valor_realizado = self.valor_previsto - desconto_passado
    end
    if self.valor_dinheiro.present? && self.valor_dinheiro > 0
      self.valor_cartao = self.valor_realizado - self.valor_dinheiro
      desconto_cartao = self.valor_cartao * (self.modopagamento.porcentagem.to_f / 100)
      valor_apos = self.valor_cartao.to_f - desconto_cartao
      self.valor_cartao = valor_apos
      self.valor_realizado = self.valor_cartao + self.valor_dinheiro
    elsif self.modopagamento_id.present?
      desconto_cartao =  self.valor_realizado * (self.modopagamento.porcentagem.to_f / 100)
      valor_apos = self.valor_realizado.to_f - desconto_cartao
      self.valor_realizado = valor_apos
    end
  end

  after_save :seta_valor_devedor
  def seta_valor_devedor
    if self.promissoria_ids.present?
      self.promissoria_ids.each do |promi|
        @promissoria = Promissoria.find(promi)
        restante = @promissoria.valor_restante - self.valor_realizado
        @promissoria.update :valor_restante => restante
      end
    end
  end

  # after_save :seta_movimentoid
  # def seta_movimentoid
  #   if params[:promissoria_id].present?
  #     @agendamento = Promissoria.find(self.promissoria_id)
  #     @agendamento.update movimento_id: self.id
  #   end
  # end

  scope :ultimo_agendamento, -> (cliente) { where(cliente_id: cliente) }

  scope :do_tipo, -> (tipo_arr) {
    if tipo_arr.include?("receita") && tipo_arr.include?("despesa")
    elsif tipo_arr.include?("receita")
      receita
    elsif tipo_arr.include?("despesa")
      despesa
    end
  }

  scope :cartaovalor, -> (cartao) { where(categoriamovimento_id: cartao) }
  scope :movimento_categoria, -> (hoje = Date.today) { where(data_realizado: hoje.beginning_of_month .. hoje.end_of_month, tipo: :despesa ) }
  scope :do_periodo, -> (inicio,fim) { where(data_realizado: inicio..fim) }
  scope :do_dia, -> (dia = Date.today) { do_periodo(dia,dia) }
  scope :data_inicio, -> (inicio) { where("data_realizado >= ?", inicio.to_date) }
  scope :data_fim, -> (fim) { where("data_realizado <= ?", fim.to_date) }
  scope :da_semana, -> (dia) { do_periodo(dia.beginning_of_week,dia_end_of_week) }
  scope :do_mes, -> (diames = Date.today) { do_periodo(diames.beginning_of_month, diames.end_of_month) }
  scope :aberto,     Proc.new { where('data_realizado is null') }
  scope :fidelidade_contemplar, -> { find_by_sql("SELECT nome,COUNT(nome) as total FROM movimentos
                                                  INNER JOIN clientes ON movimentos.cliente_id = clientes.id
                                                  WHERE fidelidade=true GROUP BY nome
                                                  ") }

  scope :pontual, -> (id) { where(cliente_id: id, pontualidade: "pontual") }
  scope :atrasada, -> (id) { where(cliente_id: id, pontualidade: "atrasou") }
  scope :pontualidadegrafico, -> { where(pontualidade: ["atrasou", "pontual"]) }

  scope :procedimento, -> { where(agendamento_id: params[:agendamento_id]) }

  scope :receita, -> { where(tipo: :receita) }
  scope :despesa, -> { where(tipo: :despesa) }

  def self.saldo_inicial(periodo, tipo_relatorio = "")
    ultimo_dia = periodo - 1.day

    receitas_realizadas = Movimento.receita.where('data_realizado <= ?', ultimo_dia).sum(:valor_realizado)
    despesas_realizadas = Movimento.despesa.where('data_realizado <= ?', ultimo_dia).sum(:valor_realizado)
    saldo_realizado     = receitas_realizadas - despesas_realizadas

    hoje = Date.today
    if ultimo_dia < hoje
      saldo_realizado
    else
      receitas_futuras = Movimento.aberto.receita.where('data_prevista between ? and ?', hoje, ultimo_dia).sum(:valor_realizado)
      despesas_futuras = Movimento.aberto.despesa.where('data_prevista between ? and ?', hoje, ultimo_dia).sum(:valor_realizado)
      saldo_futuro     = receitas_futuras - despesas_futuras

      saldo_realizado + saldo_futuro
    end
  end

  def self.total_movimentos(efeito, periodo, tipo_relatorio="DRE", tipo=nil, modopagamento=nil)
    competencia_hoje    = Date.today.strftime '%Y%m'
    competencia_periodo = periodo.strftime '%Y%m'

    if tipo_relatorio == "DRE"
      movimentos_no_periodo = Movimento.where('data_realizado = ?', periodo)
    elsif  tipo_relatorio == "FLUXOCAIXA"
      movimentos_no_periodo = Movimento.where('data_realizado between ? and ? ', periodo.beginning_of_month, periodo.end_of_month)
    end

    if efeito != 'todos'
      movimentos_no_periodo = movimentos_no_periodo.where('tipo = ?', efeito)
    end

    if tipo
      movimentos_no_periodo = movimentos_no_periodo.where('categoriamovimento_id = ?', tipo.to_s)
    end

    if modopagamento
      movimentos_no_periodo = movimentos_no_periodo.where('modopagamento_id = ?', modopagamento)
    end

    if competencia_periodo < competencia_hoje
      movimentos_no_periodo.sum(:valor_realizado)
    else
      valor_previsto  = movimentos_no_periodo.where('data_realizado is null and data_realizado > ?', Date.yesterday).sum(:valor_previsto)
      valor_realizado = movimentos_no_periodo.where('data_realizado is not null').sum(:valor_realizado)
      valor_previsto + valor_realizado
    end
  end

  def self.total_receitas(periodo, tipo_relatorio, tipo=nil, procedimento=nil)
    total_movimentos(:receita, periodo, tipo_relatorio, tipo, procedimento)
  end

  def self.total_despesas(periodo, tipo_relatorio, tipo=nil)
    total_movimentos(:despesa, periodo, tipo_relatorio, tipo)
  end

  def self.saldo_final(periodo, tipo_relatorio)
    total_receitas(periodo, tipo_relatorio) - total_despesas(periodo, tipo_relatorio)
  end

  def self.saldo_total(periodo, tipo_relatorio)
    saldo_inicial(periodo, tipo_relatorio) + saldo_final(periodo, tipo_relatorio)
  end

  def self.ver_pontuacao(cliente)
    @fidelidade = Configuracao.first
    @pontos_fidelidade = Movimento.conta_fidelidade(cliente).count
    @total = @pontos_fidelidade - cliente.fidelidade.count * 5
  end
  def self.ver_pontos(valor,cliente)
    @total = valor - Cliente.busca_cliente_fidelidade(cliente).count * 5
  end

end

app/controllers/movimentos_controller.rb
class MovimentosController < ApplicationController
  before_action :set_movimento, only: [:show, :edit, :comprovante, :update, :destroy]
  # after_filter { flash.discard if request.xhr? }, only: :toogle_status

  respond_to :html

  has_scope :do_dia, :type => :boolean
  has_scope :data_inicio
  has_scope :data_fim
  has_scope :do_mes, :type => :boolean
  has_scope :da_semana, :type => :boolean
  has_scope :do_tipo, :type => :array
  has_scope :procedimento
  has_scope :despesapendente
  has_scope :movimento_categoria, :type => :boolean
  # GET /movimentos
  # GET /movimentos.json
  def index
    # authorize Movimento, :index?
    params[:data_inicio] = l(Date.today) unless params[:data_inicio]
    params[:data_fim] = l(Date.today) unless params[:data_fim]
    @movimentos = apply_scopes(Movimento).order('id ASC').all
    @saldo = 0
    @totalreceita = @movimentos.receita.collect(&:valor_realizado).sum
    @totaldespesa = @movimentos.despesa.collect(&:valor_realizado).sum
    @contmovimentos = @movimentos.count
    @contreceita = @movimentos.receita.count
    @contdespesa = @movimentos.despesa.count
    @saldo = @totalreceita - @totaldespesa
    @modopagamento = Modopagamento.all
  end

  def fluxo

    if params[:periodo]
      @ano_referencia = params[:periodo].to_date
    else
      @ano_referencia = Date.today
    end
    # FIXME Acrescentado para evitar bugs nos dias > 28
    #       Deve ser corrigido pois pode afetar o fluxo de caixa do mês
    @ano_referencia = @ano_referencia.change(day: 1)
  end

  def dre

    if params[:periodo]
      @ano_referencia = params[:periodo].to_date
    else
      @ano_referencia = Date.today
    end
    # FIXME Acrescentado para evitar bugs nos dias > 28
    #       Deve ser corrigido pois pode afetar o fluxo de caixa do mês
    @ano_referencia = @ano_referencia.change(day: 1)
  end

  # GET /movimentos/1
  # GET /movimentos/1.json
  def show
  end

  def comprovante

  end

  def despesapendente
    mes = Date.today.beginning_of_month .. Date.today.end_of_month
    @movimentos = Movimento.where(data_realizado: nil, data_prevista: mes)
    @totaldespesa = @movimentos.despesa.collect(&:valor_previsto).sum
  end

  def gastoscategorias
    @movimentos = apply_scopes(Movimento).order('id ASC, descricao ASC')
    @categoriamovimento = Categoriamovimento.all
  end

  # GET /movimentos/new
  def new
    @movimento = Movimento.new
    @modopagamento = Modopagamento.all
    if params[:cliente_id].present?
      @movimento.cliente_id = params[:cliente_id]
    end
    if params[:venda_id].present?
      @movimento.venda_id = params[:venda_id]
      @venda = Venda.find(params[:venda_id])
    end
    if params[:promissoria_id].present?
      @movimento.promissoria_ids = params[:promissoria_id]
      @promissoria = Promissoria.find(params[:promissoria_id])
    end
  end

  def newdespesa
    @movimento = Movimento.new
    @categoria = Categoriamovimento.all
  end

  # GET /movimentos/1/edit
  def edit
    @modopagamento = Modopagamento.all
    @categoria = Categoriamovimento.all
    if params[:data_inicio].present?
      @datainicio = params[:data_inicio]
      @datafim = params[:data_fim]
    end
  end

  def editdespesa
    @categoria = Categoriamovimento.all
    if params[:data_inicio].present?
      datainicio = params[:data_inicio]
      datafim = params[:data_fim]
    end
  end

  # POST /movimentos
  # POST /movimentos.json
  def create
    @movimento = Movimento.new(movimento_params)
    @movimento.save
    respond_with(@movimento)
  end

  # PATCH/PUT /movimentos/1
  # PATCH/PUT /movimentos/1.json
  def update
    @movimento.update(movimento_params)
    if @datainicio.present?
      respond_with(@movimento, location: movimentos_path(data_inicio: @datainicio, data_fim: @datafim))
    else
      respond_with(@movimento, location: movimento_path)
    end
  end

  def toogle_status
    @movimento = Movimento.find(params[:id])
    @movimento.update_columns(fidelidade: !@movimento.fidelidade)
    # render(nothing: true)
    respond_to do |format|
      format.js { flash.now[:notice] = "Fidelidade incluida no cliente" }
    end
  end

  # DELETE /movimentos/1
  # DELETE /movimentos/1.json
  def destroy
    @movimento.destroy
    respond_to do |format|
      format.html { redirect_to movimentos_url, notice: 'Movimento excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_movimento
    @movimento = Movimento.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def movimento_params
    params.require(:movimento).permit(:valor_previsto, :data_prevista, :valor_realizado, :data_realizado, :descricao, :tipo, :desconto, :cliente_id, :modopagamento_id, :categoriamovimento_id, :agendamento_id, :pontualidade, :valor_dinheiro, :valor_cartao, :venda_id, :promissoria_ids)
  end
end

app/helpers/movimentos_helper.rb
module MovimentosHelper

  def class_valor(valor)
    estilo = if valor == 0
               'zero'
             elsif valor > 0
               'positivo'
             else
               'negativo'
             end
    "class='#{estilo}'".html_safe
  end

  def class_valor_confirmado(movimento)
    if movimento.confirmado?
      movimento.is_a?(Despesa) ? "text-danger" : "text-success"
    end
  end

  def class_valor_total
    if @saldo <= 0
      "bgm-red"
    elsif @saldo > 1
      "bgm-green"
    end
  end
end

app/views/movimentos/_formdespesa.html.erb
<%= form_for(movimento) do |f| %>
  <% if movimento.errors.any? %>
  <div id="error_explanation">

    <ul>
      <% movimento.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">

    <%= f.hidden_field :cliente_id %>

    <div class="form-group  col-sm-2 fg-float m-b-30">
      <div class="fg-line">
        <%= f.label :valor_previsto, "Valor previsto", class: "fg-label" %>
        <%= f.text_field :valor_previsto, :class => "form-control decimal_field", :maxlength => 22 %>
      </div>
    </div>

    <div class="form-group  col-sm-2 fg-float m-b-30">
      <div class="fg-line">
        <%= f.label :data_prevista, class: "fg-label" %>
        <%= f.text_field :data_prevista, class: "form-control date-picker" %>
      </div>
    </div>

    <div class="form-group  col-sm-2 fg-float m-b-30">
      <div class="fg-line">
        <%= f.label :valor_realizado, "Valor realizado", class: "fg-label" %>
        <%= f.text_field :valor_realizado, class: "form-control decimal_field" %>
      </div>
    </div>
    <div class="form-group  col-sm-3 fg-float m-b-30">
      <div class="fg-line">
        <%= f.label :data_realizado, "Data pago", class: "fg-label" %>
        <%= f.text_field :data_realizado, class: "form-control date-picker" %>
      </div>
    </div>

    <div class="form-group  col-sm-4 fg-float m-b-30">
      <div class="fg-line">
        <%= f.label :descricao, "Descrição", class: "fg-label" %>
        <%= f.text_area :descricao, class: "form-control" %>
      </div>
    </div>

    <div class="form-group col-sm-3 m-b-15">
      <div class="fg-line">
        <%= f.collection_select :categoriamovimento_id, @categoria, :id, :nome, {:prompt => 'Escolha a categoria'}, {:class => "selectpicker",  :"data-live-search" => "true", :"data-placeholder" => "Escolha a categoria da despesa"}  %>
      </div>
    </div>

    <%= f.hidden_field :tipo, :value => "despesa" %>

    <div class="form-group  col-sm-2 fg-float m-b-30">
      <div class="fg-line">
        <%= f.label :desconto, "Houve desconto?", class: "fg-label" %>
        <%= f.text_field :desconto, class: "form-control", title: "Digite aqui o valor do desconto caso tenha havido" %>
      </div>
    </div>

    <div class="form-group  col-sm-9 fg-float m-b-30">
      <div class="fg-line">
        <%= f.button 'Salvar', class: "btn btn-primary btn-lg" %>
        <%= link_to 'Voltar', movimentos_path, class: "btn btn-default" %>
      </div>
    </div>
    <% end %>

  </div>

app/views/movimentos/despesapendente.html.erb
<div class="c-header">
  <h2>Financeiro</h2>
</div>

<div class="card">

  <div class="card-header">
    <h2>Despesas pendente <small>Lista de todas as despesas pendente</small></h2>
    <ul class="actions">

      <li class="dropdown hidden-xs hidden-sm h-apps">
        <a data-toggle="dropdown" href="" aria-expanded="false">
          <i class="zmdi zmdi-search zmdi-hc-fw"></i>
        </a>
        <ul class="dropdown-menu pull-right">
          <%= render 'formsearch', movimento: @movimento %>
        </ul>
      </li>
    </ul>
  </li>
</ul>
</div>

<div class="card-body table-responsive">

  <div class="form-group  col-sm-6 fg-float m-b-30">
    <div class="fg-line">
      <%= link_to newdespesa_movimentos_path, class: "btn btn-danger" do %>
      <span class="zmdi zmdi-minus-circle"></span> Nova despesa
      <% end %>
      <%= link_to new_movimento_path, class: "btn btn-success" do %>
      <span class="zmdi zmdi-plus-circle"></span> Nova receita
      <% end %>
    </div>
  </div>

  <p id="notice" class="text-success"><%= notice %></p>

  <table class="table">
    <thead>
      <tr>
        <th>Descricao</th>
        <th>Fornecedor</th>
        <th class="text-right">Valor previsto</th>
        <th class="text-right">Data prevista</th>
        <th>Tipo</th>
        <th class="text-center">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @movimentos.each do |movimento| %>
      <tr>
        <td><%= movimento.descricao %></td>
        <td><% if movimento.cliente.present? %> <%= movimento.cliente.nome %><% end %></td>
        <td class="text-right"><%= movimento.valor_previsto %></td>
        <td class="text-right"><%= movimento.data_prevista %></td>
        <td class="danger c-white"> <%= movimento.tipo %></td>
        <td class="text-center">
          <%= link_to movimento, class: "btn btn-info btn-xs" do %>
          <span class="zmdi zmdi-eye"></span> Ver
          <% end %>
          <%= link_to edit_movimento_path(movimento), class: "btn btn-warning btn-xs" do %>
          <span class="zmdi zmdi-edit"></span> Editar
          <% end %>
          <%= link_to movimento, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse movimento?' }, class: "btn btn-danger btn-xs" do %>
          <span class="zmdi zmdi-delete"></span> Excluir
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>
</div>

<div id="c-grid" class="clearfix">
  <div class="column size-1of2">
    <div class="card c-dark palette-Red-400 bg">
      <div class="card-header">
        <h2>Valor total das despesas pendentes</h2>

      </div>
      <div class="card-body card-padding">
        <h2 class="m-t-0 m-b-15 c-white">
          <i class="zmdi zmdi-minus-circle m-r-5"></i>
          R$ <%= @totaldespesa %>
        </h2>
        <div class="sparkline-3 text-center"></div>
      </div>
    </div>
  </div>
</div>

app/views/movimentos/show.html.erb
<div class="card">

  <div class="card-header">
    <h2 class="text-uppcase">
      Comprovante de pagamento
    </h2><p></p>

    <div class="card-body card-padding">
      <div class="row">
        <div class="form-group col-sm-4">
          <div id="flash" class="text-success">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-sm-6">
          <% if notice.present? %>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <%= notice %>
          </div>
          <% end %>
          <div class="table-responsive">
            <table class="table table-condensed">
              <tbody>
                <% if @movimento.cliente.present? %>
                <tr>
                  <td><strong>Cliente</strong></td>
                  <td>
                    <%= link_to @movimento.cliente do %>
                    <strong><%= @movimento.cliente.nome %></strong>
                    <% end %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <strong>Incluir fidelidade</strong>
                  </td>
                  <td>
                    <% if @movimento.fidelidade %>
                    <div class="toggle-switch" data-ts-color="green">
                      <input id="ts4" onchange="toggle_status(<%= @movimento.id %>);" checked type="checkbox" hidden="hidden">
                      <label for="ts4" class="ts-helper"></label>
                    </div>
                    <% else %>
                    <div class="toggle-switch" data-ts-color="green">
                      <input id="ts4" onchange="toggle_status(<%= @movimento.id %>);" type="checkbox" hidden="hidden">
                      <label for="ts4" class="ts-helper"></label>
                    </div>
                    <% end %>

                  </td>
                </tr>
                <% end %>
                <% if @movimento.categoriamovimento.present? %>
                <tr class="danger c-white">
                  <td><strong>Categoria despesa</strong></td>
                  <td><%= @movimento.categoriamovimento.nome %></td>
                </tr>
                <% end %>
                <tr>
                  <td><strong>Valor previsto</strong></td>
                  <td><%= @movimento.valor_previsto %></td>
                </tr>
                <tr>
                  <td><strong>Data Prevista</strong></td>
                  <td><%= @movimento.data_prevista %></td>
                </tr>
                <% if @movimento.valor_dinheiro.present? && @movimento.valor_dinheiro > 0 %>
                <tr>
                  <td><strong>Valor pago em dinheiro</strong></td>
                  <td><%= @movimento.valor_dinheiro %></td>
                </tr>
                <tr>
                  <td><strong>Valor pelo <%= @movimento.modopagamento.tipo %></strong></td>
                  <td><%= @movimento.valor_cartao %></td>
                </tr>
                <% end %>
                <tr>
                  <td><strong>Valor total pago</strong></td>
                  <td><%= @movimento.valor_realizado %></td>
                </tr>
                <tr>
                  <td><strong>Data Pago</strong></td>
                  <td><%= @movimento.data_realizado %></td>
                </tr>
                <tr>
                  <td><strong>Desconto</strong></td>
                  <td><% if @movimento.desconto.present? %><%= @movimento.desconto %> <% else %> <i>não houve</i> <% end %></td>
                </tr>
                <% if @movimento.modopagamento.present? %>
                <tr>
                  <td><strong>Modo de pagamento</strong></td>
                  <td><abbr title="<%= @movimento.modopagamento.porcentagem %>%"><%= @movimento.modopagamento.tipo %></td>
                  </tr>
                  <% end %>
                  <% if @movimento.tipo == "despesa" %>
                  <tr>
                    <td><strong>Tipo movimento</strong></td>
                    <td><button class="btn btn-danger btn-xs"><%= @movimento.tipo %></button></td>
                  </tr>
                  <% else %>
                  <tr>
                    <td><strong>Tipo movimento</strong></td>
                    <td><button class="btn btn-success btn-xs"><%= @movimento.tipo %></button></td>
                  </tr>
                  <% end %>

                  <% if @movimento.agendamento.present? %>
                  <tr>
                    <td><strong>Procedimentos</strong></td>
                    <td>
                      <% @movimento.agendamento.procedimentos.each do |ag| %>
                      <%= link_to @movimento.agendamento,  class: "badge" do %>
                      <%= ag.nome %>
                      <% end %>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>

                  <tr>
                    <td><strong>Descrição</strong></td>
                    <td><%= @movimento.descricao %></td>
                  </tr>
                </table>
              </div>

            </div>
          </div>
          <div class="row">
            <div class="col-xs-16">
              <%= link_to cliente_path(@movimento.cliente), class: "btn btn-success" do %>
              <span class="zmdi zmdi-check-all"></span> Concluir
              <% end %>
              <% if @movimento.tipo == "receita" %>
              <%= link_to comprovante_movimentos_path(id: @movimento), class: "btn btn-primary" do %>
              <span class="zmdi zmdi-eye"></span> Comprovante
              <% end %>
              <% end %>
              <%= link_to edit_movimento_path(@movimento), class: "btn btn-warning" do %>
              <span class="zmdi zmdi-edit"></span> Editar
              <% end %>
              <%= link_to 'Voltar', movimentos_path, class: "btn btn-default" %>
              <%= link_to @movimento, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse movimento?' }, class: "btn btn-danger pull-right" do %>
              <span class="zmdi zmdi-delete"></span> Excluir
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <button class="btn btn-float bgm-red m-btn" data-action="print"><i class="zmdi zmdi-print"></i></button>

    <script>
    function toggle_status(id) {
      $.ajax({
        url:'/movimentos/'+id+'/toogle_status',
        type: 'GET'
      }).success(function(data) {
        $("#flash").html("Fidelidade modificada")
      });
    }
    </script>